// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdNa0ivUR7sxsRZkiUhHnMhso5hDpbmM',
    appId: '1:1000419999434:web:16ab088e66701c0c843e33',
    messagingSenderId: '1000419999434',
    projectId: 'notes-106',
    authDomain: 'notes-106.firebaseapp.com',
    storageBucket: 'notes-106.firebasestorage.app',
    measurementId: 'G-7HBJR0ENYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWu0meYQOaBZmV2JGp1Cbf8Iu0qO_4_E0',
    appId: '1:1000419999434:android:f5315d7de62cbec6843e33',
    messagingSenderId: '1000419999434',
    projectId: 'notes-106',
    storageBucket: 'notes-106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Qnp-I7zX5hDoMH5FwxUaoe-Qu1NNqeA',
    appId: '1:1000419999434:ios:d41631d06a70c122843e33',
    messagingSenderId: '1000419999434',
    projectId: 'notes-106',
    storageBucket: 'notes-106.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Qnp-I7zX5hDoMH5FwxUaoe-Qu1NNqeA',
    appId: '1:1000419999434:ios:d41631d06a70c122843e33',
    messagingSenderId: '1000419999434',
    projectId: 'notes-106',
    storageBucket: 'notes-106.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdNa0ivUR7sxsRZkiUhHnMhso5hDpbmM',
    appId: '1:1000419999434:web:fab811937cdc6a0d843e33',
    messagingSenderId: '1000419999434',
    projectId: 'notes-106',
    authDomain: 'notes-106.firebaseapp.com',
    storageBucket: 'notes-106.firebasestorage.app',
    measurementId: 'G-HHPRKJNZ3B',
  );
}
